buildlib:
	g++ -std=c++2b -I./../../include -c ./../../src/integrate.cpp

buildtest:
	g++ -std=c++2b -o test -I./../../include /home/tobiasb/OneDrive/projects/PDFcode/openqcdrad-2.1/qcdlib/gauss.o ./integrate.o ./test.cpp -lgsl